name: 'reusable/validate'

on:
  workflow_call:
    secrets:
      TF_MODULES_APP_ID:
        description: 'Terraform modules GitHub Application ID'
        required: false

      TF_MODULES_APP_PRIVATE_KEY:
        description: 'Terraform modules GitHub Application private key'
        required: false

    inputs:
      terraformVersion:
        description: 'Defines terraform version to use'
        required: true
        type: string

      moduleRootDirectory:
        description: 'Defines root module directory'
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.moduleRootDirectory }}
    steps:
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraformVersion }}

      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate GitHub App token
        env:
          APP_ID: ${{ secrets.TF_MODULES_APP_ID }}
          PRIVATE_KEY: ${{ secrets.TF_MODULES_APP_PRIVATE_KEY }}
        if: ${{ env.APP_ID != null && env.PRIVATE_KEY != null }}
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TF_MODULES_APP_ID }}
          private_key: ${{ secrets.TF_MODULES_APP_PRIVATE_KEY }}

      - name: Authenticate to GitHub with GitHub App token
        env:
          APP_ID: ${{ secrets.TF_MODULES_APP_ID }}
          PRIVATE_KEY: ${{ secrets.TF_MODULES_APP_PRIVATE_KEY }}
        if: ${{ env.APP_ID != null && env.PRIVATE_KEY != null }}
        run: |
          echo ${{ steps.generate_token.outputs.token }} | gh auth login --with-token
          gh auth setup-git

      - name: Format
        run: |
          terraform fmt -write=false -diff -check

      - name: Validate
        run: |
          terraform init --backend=false
          terraform validate
